---
slug: :mikutter-command-save_as_oembed
depends:
  mikutter: 3.2.0
  plugin:
  - command
  - settings
version: '0.0.1'
author: moguno
name: mikutter-command-save_as_oembed
description: 選択したメッセージをhtml形式で保存するコマンド
